"""empty message

Revision ID: 500ea632c641
Revises: 97feae1aeb80
Create Date: 2023-02-22 02:04:46.836611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500ea632c641'
down_revision = '97feae1aeb80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('list_id')

    op.drop_table('todolists')
    # ### end Alembic commands ###
